// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcppPrecompute
List rcppPrecompute(NumericVector lower, NumericVector upper, NumericVector mean, NumericMatrix coval);
RcppExport SEXP lwafomps_rcppPrecompute(SEXP lowerSEXP, SEXP upperSEXP, SEXP meanSEXP, SEXP covalSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coval(covalSEXP);
    __result = Rcpp::wrap(rcppPrecompute(lower, upper, mean, coval));
    return __result;
END_RCPP
}
// rcppMvnorm
double rcppMvnorm(List rcpData, int shift);
RcppExport SEXP lwafomps_rcppMvnorm(SEXP rcpDataSEXP, SEXP shiftSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< List >::type rcpData(rcpDataSEXP);
    Rcpp::traits::input_parameter< int >::type shift(shiftSEXP);
    __result = Rcpp::wrap(rcppMvnorm(rcpData, shift));
    return __result;
END_RCPP
}
