# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppPrecompute <- function(lower, upper, mean, coval) {
    .Call('lwafomps_rcppPrecompute', PACKAGE = 'lwafomps', lower, upper, mean, coval)
}

rcppMvnorm <- function(rcpData, shift) {
    .Call('lwafomps_rcppMvnorm', PACKAGE = 'lwafomps', rcpData, shift)
}

